### ISSUE TITLE
Feature Request: Upload Build Info

### ISSUE THREAD

**Issue by cdhunt** [OctopusDeploy/cli#120]
Example based on the new syntax with the existing `octo build-information` command.
`octopus package build-info --package utils --version 1.2.3 --file`

**Comment by tijmenpitcrew** [comment]
This blocks us from upgrading from `octo` as well.

**Comment by picknick3r** [comment]
Is there any update on this feature? This is blocking us from upgrading from octo as well :(

**Comment by hnrkndrssn** [comment]
FYI we have shipped `v2.5.0` of the cli which includes a command to upload build info to Octopus.
