### ISSUE TITLE
octopus space delete --confirm does not delete the space

### ISSUE THREAD

**Issue by borland** [OctopusDeploy/cli#131]
Repro:

- Create a space
- run `octopus space delete "SpaceNameHere" --confirm`
- Expected: the space to get deleted
- Observed: the cli just exits with no output or warnings and the space is not deleted

I also tried "--confirm y", "--confirm=yes", "--confirm yes" and other variations like that.

Deleting spaces does work if you don't supply `--confirm` and go through the interactive confirmation.

Root cause is this code here:

https://github.com/OctopusDeploy/cli/blob/18b36f680e56a9d91d31658b208382da57f2d2c2/pkg/cmd/space/delete/delete.go#L51

The `delete` function call only runs if it's inside the question DeleteWithConfirmation callback, where it should run on both sides of the `if !alreadyConfirmed` branch

**Comment by benPearce1** [comment]
@borland it appears that https://github.com/OctopusDeploy/cli/pull/169 fixes this issue, is that correct?
