### ISSUE TITLE
Octopus API error: The Resource field is required. []

### ISSUE THREAD

**Issue by mieliespoor** [OctopusDeploy/cli#217]
For some unknown reason, we are getting the following error back from the cli

`Octopus API error: The Resource field is required. []`

This is the the exact call we do, with parameter values

```
.\octopus.exe release create --project "package-update-downloader" --version "1.0.0-initial-commit.4177" --package-version "1.0.0-initial-commit.4177" --channel "Release" --release-notes "release 1.0.0-initial-commit.4177 commit -- 3c5541f4b71f9263929c7c1d241b6af05791ac05" --space "Default" --no-prompt
```

Note that the following were set as ENV vars. `OCTOPUS_API_KEY` and `OCTOPUS_URL`

I have run the above on Windows, but we see the same happening on Linux.

**Comment by benPearce1** [comment]
Hi @mieliespoor 

I tested the above command using v1.1 of the cli and the most recent version of Octopus Server, without issue.

There is a requirement of 2022.3 to be able to use some of functionality in the cli (these are `release create`, `release deploy`, `runbook run`).

**Comment by mieliespoor** [comment]
We are on 2022.2 build 10847. We are thus on the correct minimum version. My main problem here is that the message returned is completely useless. I tried is on my own machine in various formats and keep getting that error, so something is most definitely broken in the cli.

**Comment by benPearce1** [comment]
@mieliespoor you are correct that the error message is unhelpful. I have raised an issue https://github.com/OctopusDeploy/cli/issues/221 to specifically address the unhelpful messaging in this scenario.

In the meantime, the only workaround I can suggest is to upgrade your server to 2022.3 or later.

**Comment by mieliespoor** [comment]
Apologies, I made a typo. We are running 2022.3.

**Comment by benPearce1** [comment]
Are you able to provide me with exact server version number you are running and I will try to recreate your issue?

**Comment by mieliespoor** [comment]
All I can see in Octopus is 2022.3 build 10847. Not sure what other version information there is.
![image](https://user-images.githubusercontent.com/5008243/216039809-b3a0155d-0d70-4e49-a1f1-60419f470156.png)

**Comment by mieliespoor** [comment]
Any feedback on this?

**Comment by benPearce1** [comment]
Sorry for the slow response. 
I haven't been able to recreate the error you are seeing, even running against the exact same server version you are using.
The artifact attached to [this branch build](https://github.com/OctopusDeploy/cli/actions/runs/4351393788) of the cli, contains an updated cli which is an experiment on improving the debug output.
You will to update the version of `octopus` that you are running with the Windows exe contained in the zip file, and also need to add `--debug` to the command you are running. This should produce a stack trace of the failure point.

**Comment by benPearce1** [comment]
@mieliespoor From the additional information provided in the support ticket you raised, it appears that it may be case-sensitivity when matching up the name of the project. This is only the case when the project query has been cached in memory, if the query has to go out to the database, it is dependant on the collation of the database.
This issue has been fixed in the most recent server versions.

Can you please try modifying your `--project` parameter to ensure the value exactly matches the name of the target project?

**Comment by mieliespoor** [comment]
Hi Ben,
I have asked one of the guys in the team to do more tests and submit more information on the support ticket. One of the projects that was sent through on the support ticket had the casing issue and fixing that solved it. In this particular instance (the project in the first post), the project name has always been lower case. We will hopefully be able to give the additional info on the support ticket tomorrow.

**Comment by benPearce1** [comment]
@lhalleyvzc thanks for getting back to me.

From the stack trace in the error, I can see that this is caused by an error being returned from the Octopus API. This is still suggesting that one of the resource names in the command (project, channel or space) doesn't match the casing of the resource in the server.

**Comment by mieliespoor** [comment]
I'm closing this since upgrading Octopus and the cli seemed to have fixed it for us. No point keeping this open anymore
