### ISSUE TITLE
unknown command "list-latestdeployments" for "octopus"

### ISSUE THREAD

**Issue by olsh** [OctopusDeploy/cli#223]
## The bug

The new CLI doesn't have [`list-latestdeployments`](https://octopus.com/docs/octopus-rest-api/octopus-cli/list-latestdeployments) command

## Command to reproduce

```
octopus list-latestdeployments
```

## Outcome

```
unknown command "list-latestdeployments" for "octopus"
```

## Versions

**cli**: 1.2.0

**Octopus Server**: Cloud

**Comment by olsh** [comment]
It turned out that the new CLI has `octopus release list` command.
Sorry for the noise.

**Comment by odin568** [comment]
Also searching for a replacement for listing latest deployment. I can see releases with `octopus release list` but how can I determine what is deployed to a given environment?
