### ISSUE TITLE
installation fails on ubuntu 22.10

### ISSUE THREAD

**Issue by trondhindenes** [OctopusDeploy/cli#264]
## The bug

I'm getting this error when trying to install the package via the documented apt commands. Ubuntu 22.10 includes `[libicu71](https://packages.ubuntu.com/kinetic/libicu71)` so the dependency tree for octopus probably needs to be updated to support newer ubuntu versions.

## Command to reproduce

```
# after having set up the apt source as documented
sudo apt install octopuscli
```

## Outcome

```
The following packages have unmet dependencies:
 octopuscli : Depends: libicu52 but it is not installable or
                       libicu55 but it is not installable or
                       libicu57 but it is not installable or
                       libicu60 but it is not installable or
                       libicu63 but it is not installable or
                       libicu66 but it is not installable or
                       libicu67 but it is not installable or
                       libicu70 but it is not installable

```

## Versions

**cli**: latest available

**Octopus Server**: N/A

**Comment by benPearce1** [comment]
Hi @trondhindenes 
The application that you are trying to install is the deprecated CLI written in .Net.
This is the newer CLI and its installation instructions are [here](https://github.com/OctopusDeploy/cli#linux-debianubuntu-based-distributions). I tested it on Ubuntu 22.10 and it worked successfully.
