### ISSUE TITLE
Clarity around auto-selection of spaces

### ISSUE THREAD

**Issue by borland** [OctopusDeploy/cli#30]
The current behavior of the CLI is as follows:

- If the `OCTOPUS_SPACE` environment variable is populated, the CLI will always try and use it; If no such space exists, the CLI will fail, rather than prompting for selection
- The CLI doesn't know whether `OCTOPUS_SPACE` contains a name or ID, so before doing anything it will go to the server and first search by ID, then by Name.

- If `OCTOPUS_SPACE` is not populated, then when running in automation mode the CLI will simply fail

- If `OCTOPUS_SPACE` is not populated, when running interactively, the CLI will ask the server for the list of spaces:
   - If there are no spaces, we fail
   - If there is only one space, the CLI will automatically select it
   - If there is more than one space, the CLI will prompt the user to select one.

Q: Should we reverse the space search order, and check by name first and then fallback to ID?

Q: In the case where there is only one space, the CLI simply uses it. It doesn't pay any attention to the notion of "Default Space" that the Octopus server has. Should we consider perhaps only auto-selecting if there is one space _and_ the server says it is the default space?

**Comment by jbristowe** [comment]
Relates to #29

**Comment by slewis74** [comment]
For context, server will always have at least 1 space, it has no concept of "no spaces".

Q1: for other clients we've done a single pass/query that will match on either name or ID. e.g. `WHERE Name == providedValue || Id == providedVale`.

Q2: I think we should ignore the default space flag altogether.

Related to the hard fail if the environment variable points to a space that doesn't exist, in interactive mode I'm not sure about this. In fact I'm wondering about whether it should treat it only as the default option but still show the list if there's more than 1, for interactive mode only. It is likely that users have a space they will predominantly be working in, but that doesn't mean they always use that space. Should they have to change the env var to switch spaces if they are working across multiple spaces? Maybe that's not unreasonable, I'm not sure yet.

Sort of related to this. In the portal the browser remembers which space you were last working in and brings you back there next login. If there's an interactive list for space selection I wonder if selecting the last one you used as a default might be of value?

**Comment by borland** [comment]
Thanks @slewis74 - per discussion I'll make the logic match a name before an ID, and follow the typescript client's way of enumerating all the spaces and doing the selection client side. This may not perform well if there are a very many spaces, but the common case is for a few (< 30) so we can do it in one network call (otherwise looking up name, then ID would incur two calls)

Also per discussion, the server will always have at least one space, but permissions may not allow you to see it. It's easy to simply fail out the CLI with an error message in that case so will do that.

Will remove any mention in TODO's / of consideration for the "Default space" as we've agreed the CLI will not pay attention to that.

**Comment by borland** [comment]
Code was all implemented as per the above discussion
