### ISSUE TITLE
Missing delta compression from octopus package upload

### ISSUE THREAD

**Issue by eero-dev** [OctopusDeploy/cli#303]
We tried to use the new version of https://github.com/OctopusDeploy/install-octopus-cli-action which installs the Go CLI, but it renders our CI unusable

Our Github Actions release workflow generates 300MB of packaged files (multiple .NET projects), in 10 different zip files which are uploaded to Octopus Deploy Cloud and deployed to customers

The old .NET CLI supported delta compression, making `octo push` really fast
![image](https://github.com/OctopusDeploy/cli/assets/49983218/38861ea8-a457-4b84-950f-47584f8ca4bc)

The new CLI doesnt support delta compression, making `octopus package upload` really slow and unusable in Github Actions workflow
![image](https://github.com/OctopusDeploy/cli/assets/49983218/67db489b-0520-4904-a279-5bb848a03950)

The old parameter in `octo push` used to be:
```
  --use-delta-compression=VALUE
                             Allows disabling of delta compression when
                             uploading packages to the Octopus Server. (True
                             or False. Defaults to true.)
```

https://octopus.com/docs/octopus-rest-api/octopus-cli/push

I would like to see this feature added back to `octopus package upload`  to have feature parity with `octo push`

**Comment by danzhik** [comment]
https://github.com/OctopusDeploy/cli/pull/226#issuecomment-2167994226

**Comment by eero-dev** [comment]
This has been implemented, thanks.
