### ISSUE TITLE
Bug: Cannot use base "Octopus" command with no parameters

### ISSUE THREAD

**Issue by MudraR** [OctopusDeploy/cli#329]
## The bug

While able to use base commands such as `octopus login` or even just `octo`,  using `octopus` is giving out a verbose error after the recent addition of the [commandDoesNotRequireClient](https://github.com/OctopusDeploy/cli/commit/f75584156b04bec28d41def60360e5953acce0a6) function.

I downgraded to v2.1.0 and tested to confirm that this error is v2.1.1 specific.

## Command to reproduce

```
octopus
```

## Outcome

<img width="296" alt="image" src="https://github.com/OctopusDeploy/cli/assets/67904550/e2002638-b859-4f08-bf9d-0346f2352765">

## Versions

**cli**: [2.1.1](https://github.com/OctopusDeploy/cli/releases/tag/v2.1.1)

**Octopus Server**: N/A

## Links

Using `octopus` should still be supported according to the latest [docs](https://octopus.com/docs/octopus-rest-api/cli/octopus).

**Comment by MudraR** [comment]
Created [PR](https://github.com/OctopusDeploy/cli/pull/330) for this.

**Comment by benPearce1** [comment]
@MudraR Thanks for your contribution. This has been fixed in #336
