### ISSUE TITLE
No respect of colour scheme for white background terminal

### ISSUE THREAD

**Issue by nuuantoine** [OctopusDeploy/cli#345]
## The bug

If using octo in WSL with windows terminal and white background the output is not readable at all.

## Command to reproduce
![image](https://github.com/OctopusDeploy/cli/assets/112953922/4084f35d-5246-4d16-8e0e-d72396381cdc)

## Versions
9.1.7

**cli**:
octo

**Comment by benPearce1** [comment]
@nuuantoine The screenshot you have provided is for the [deprecated cli](https://github.com/OctopusDeploy/OctopusCLI).
Could you test the output with the [newer cli](https://github.com/OctopusDeploy/cli/releases/tag/v2.2.1) and update this issue if it is still showing the same output behaviour?
