### ISSUE TITLE
CLI Configuration

### ISSUE THREAD

**Issue by jbristowe** [OctopusDeploy/cli#35]
The CLI should support a `config` command that provides the user to control the CLI configuration.

### Commands

* `octopus config get`: print the value of a given configuration key
* `octopus config set`: update configuration with a value for the given key
* `octopus config list`: print a list of configuration keys and values

### Configuration Settings

* `api_key`: the API key to be used to communicate with Octopus Deploy
* `editor`: the text editor program to use for authoring text
* `host`: the host URI of Octopus Deploy
* `prompt`: toggle interactive prompting in the terminal (default: `"enabled"`)
* `space`: the space within which to perform operations in Octopus Deploy

**Comment by borland** [comment]
`config get` and `config set` are implemented in v0.2.3 of the CLI
`config list` is not yet implemented

**Comment by domenicsim1** [comment]
Config list is implemented
