### ISSUE TITLE
One or more deployment tasks failed

### ISSUE THREAD

**Issue by piyush94** [OctopusDeploy/cli#421]
## The bug

octopus release deploy command says **One or more deployment tasks failed.** even though there is no error in the task log.

## Command to reproduce

```
octopus --space Default --no-prompt release deploy --project My_Project  --environment Development01 --version $release_version --update-variables --output-format basic
```

## Outcome

```
Deploy My_Project release 0.0.69 to Development01: Executing
Deploy My_Project release 0.0.69 to Development01: Success
One or more deployment tasks failed.
```

## Versions

**cli**: 2.10.1

**Octopus Server**: 2024.3.12735

**Comment by ukaan01** [comment]
might be because of this change 
![image](https://github.com/user-attachments/assets/7981eda8-91cf-4694-a736-7e49a200e9f0)

I'd assume that we need to check IsCompleted and only after that FinishedSuccessfully

@jameschensmith FYI ^

**Comment by jameschensmith** [comment]
Oof. I'll see if I can look into that today. Thanks for the ping, @ukaan01.

**Comment by jameschensmith** [comment]
#422 should fix this issue.
